### ISSUE TITLE
Exception when using audit hook

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#374]
```java
2015-04-16 10:44:46,623 [hystrix-CreateEntityMetadataCommand-2] ERROR [com.redhat.lightblue.metadata.parser.MetadataParser] com.mongodb.BasicDBObject cannot be cast to com.fasterxml.jackson.databind.JsonNode: java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to com.fasterxml.jackson.databind.JsonNode
	at com.redhat.lightblue.hook.audit.AuditHookConfigurationParser.convert(AuditHookConfigurationParser.java:13)
	at com.redhat.lightblue.metadata.parser.MetadataParser.convertHooks(MetadataParser.java:1279)
	at com.redhat.lightblue.metadata.parser.MetadataParser.convert(MetadataParser.java:885)
	at com.redhat.lightblue.metadata.mongo.BSONParser.convert(BSONParser.java:197)
	at com.redhat.lightblue.metadata.mongo.MongoMetadata.updateEntityInfo(MongoMetadata.java:349)
	at com.redhat.lightblue.rest.metadata.hystrix.CreateEntityMetadataCommand.run(CreateEntityMetadataCommand.java:75)
	at com.redhat.lightblue.rest.metadata.hystrix.CreateEntityMetadataCommand.run(CreateEntityMetadataCommand.java:36)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by luan-cestari** [comment]
@dcrissman , I will close this issue as it seems duplicated with https://github.com/lightblue-platform/lightblue-audit-hook/issues/28  . Re open the issue if you think it is another problem
