### ISSUE TITLE
Bug when performing find on entity with hook

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#376]
After fixing https://github.com/lightblue-platform/lightblue-audit-hook/issues/28, I am now getting this exception from data nodes when I execute a find against the entity.

```
2015-04-17 10:35:03,962 [hystrix-FindCommand-10] ERROR [com.redhat.lightblue.crud.mongo.MongoCRUDController] null: java.lang.NullPointerException
	at com.redhat.lightblue.hooks.HookManager.queueHooks(HookManager.java:198)
	at com.redhat.lightblue.hooks.HookManager.queueHooks(HookManager.java:141)
	at com.redhat.lightblue.crud.mongo.MongoCRUDController.find(MongoCRUDController.java:347)
	at com.redhat.lightblue.mediator.SimpleFindImpl.find(SimpleFindImpl.java:52)
	at com.redhat.lightblue.mediator.Mediator.find(Mediator.java:346)
	at com.redhat.lightblue.rest.crud.hystrix.FindCommand.run(FindCommand.java:66)
	at com.redhat.lightblue.rest.crud.hystrix.FindCommand.run(FindCommand.java:36)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bserdar** [comment]
Line 198 is:

           CRUDHook crudHook = resolver.getHook(h.getName());

My guess is that the hook has null name.

**Comment by bserdar** [comment]
No, that's not right. Either the 'resolver' is null, or 'h' is null.

**Comment by dcrissman** [comment]
Relevant section of metadata
```json
        "hooks": [
            {
                "name": "auditHook",
                "configuration": {
                    "entityName": "audit",
                    "version": "1.0.0"
                },
                "actions": [
                    "insert",
                    "update",
                    "delete"
                ]
            }
        ]
```

**Comment by dcrissman** [comment]
An insert on the entity has the same issue:
```
2015-04-17 11:22:40,486 [hystrix-InsertCommand-1] ERROR [com.redhat.lightblue.crud.mongo.MongoCRUDController] saveOrInsert failed: {}: java.lang.NullPointerException
        at com.redhat.lightblue.hooks.HookManager.queueHooks(HookManager.java:198)
        at com.redhat.lightblue.hooks.HookManager.queueHooks(HookManager.java:141)
        at com.redhat.lightblue.crud.mongo.MongoCRUDController.saveOrInsert(MongoCRUDController.java:164)
        at com.redhat.lightblue.crud.mongo.MongoCRUDController.insert(MongoCRUDController.java:100)
        at com.redhat.lightblue.mediator.Mediator.insert(Mediator.java:107)
        at com.redhat.lightblue.rest.crud.hystrix.InsertCommand.run(InsertCommand.java:65)
        at com.redhat.lightblue.rest.crud.hystrix.InsertCommand.run(InsertCommand.java:36)
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
        at rx.Observable$1.call(Observable.java:144)
        at rx.Observable$1.call(Observable.java:136)
        at rx.Observable$1.call(Observable.java:144)
        at rx.Observable$1.call(Observable.java:136)
        at rx.Observable$1.call(Observable.java:144)
        at rx.Observable$1.call(Observable.java:136)
        at rx.Observable.unsafeSubscribe(Observable.java:7466)
        at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514)
        at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497)
        at rx.Observable.unsafeSubscribe(Observable.java:7466)
        at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by bserdar** [comment]
I believe Factory.hookResolver is never set, so it is null.

It should be set in LightblueFactory.initializeFactory.

**Comment by luan-cestari** [comment]
Yeah, I experience that in some tests and briefly described the root cause of the problem ( why  resolver is null) on our itnernal IRC channel. I'm fixing it

**Comment by bserdar** [comment]
Lcestari, one way of fixing it is to have a list of all available hook
classes in the crud config. Are you doing that, or do you have a better
solution?

**Comment by dcrissman** [comment]
I assume this auto-closed, but it is still being worked on.

**Comment by luan-cestari** [comment]
@dcrissman I think it is working fine now. Could you report here if you find any issue on your smoke test s using audit hook please? Maybe it can be a new issue and we can close this one.

**Comment by dcrissman** [comment]
All PRs merged, I will push out test.

**Comment by dcrissman** [comment]
Having some build issues that are preventing me from testing. I am still working on this and hope to have an answer soon.

**Comment by dcrissman** [comment]
fixed
